name: auto-publish

on:
  # push:
  #   branches:
  #     - main
  release:
    types: [published]

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: My-Tasks
        run: |
          npm install
          npm run package

      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.token }}
