name: auto-publish

on:
  push:
    branches:
      - main

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: My-Tasks
        run: |
          npm install
          npm run package

      - uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
