name: auto-publish

on:
  push:
    branches:
      - main

jobs:
  auto-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: My-Tasks
        run: |
          npm install -g vsce
          vsce package
          vsce publish -p ${{ github.token }}

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ./*.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
